services:
  - type: web
    name: eventregistrationfrontend-main18
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
